# Generated by Django 5.2.6 on 2025-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
