# Generated by Django 5.2.6 on 2025-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_membre_remove_dvd_emprunteur_remove_cd_emprunteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
            preserve_default=False,
        ),
    ]
